package LiteratureAnalytics.ui;

import LiteratureAnalytics.vocab.Vocabulary;
import org.jsoup.Jsoup;

import javax.swing.*;
import javax.swing.text.Document;
import javax.swing.text.html.HTMLEditorKit;
import java.io.File;
import java.io.IOException;

public class LiteratureAnalyticsUI extends javax.swing.JFrame {

    Vocabulary vocab;

    /**
     * Creates new form LiteratureAnalyticsUI
     */
    public LiteratureAnalyticsUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        topPanel = new javax.swing.JPanel();
        inputTextButton = new javax.swing.JButton();
        leftPanel = new javax.swing.JPanel();
        rightPanel = new javax.swing.JPanel();
        htmlScrollPane = new javax.swing.JScrollPane();
        htmlEditorPane = new javax.swing.JEditorPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        topPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ανάλυση Λογοτεχνικών Κειμένων", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        inputTextButton.setBackground(new java.awt.Color(255, 0, 51));
        inputTextButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        inputTextButton.setText("Εισαγωγή Κειμένου");
        inputTextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputTextButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout TopPanelLayout = new javax.swing.GroupLayout(topPanel);
        topPanel.setLayout(TopPanelLayout);
        TopPanelLayout.setHorizontalGroup(
                TopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(TopPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(inputTextButton)
                                .addContainerGap(428, Short.MAX_VALUE))
        );
        TopPanelLayout.setVerticalGroup(
                TopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TopPanelLayout.createSequentialGroup()
                                .addComponent(inputTextButton, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                                .addContainerGap())
        );

        leftPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Επιλογή Ανάλυσης", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        javax.swing.GroupLayout LeftPanelLayout = new javax.swing.GroupLayout(leftPanel);
        leftPanel.setLayout(LeftPanelLayout);
        LeftPanelLayout.setHorizontalGroup(
                LeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 157, Short.MAX_VALUE)
        );
        LeftPanelLayout.setVerticalGroup(
                LeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 280, Short.MAX_VALUE)
        );

        htmlEditorPane.setEditable(false);
        htmlScrollPane.setViewportView(htmlEditorPane);

        javax.swing.GroupLayout RightPanelLayout = new javax.swing.GroupLayout(rightPanel);
        rightPanel.setLayout(RightPanelLayout);
        RightPanelLayout.setHorizontalGroup(
                RightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(RightPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(htmlScrollPane)
                                .addContainerGap())
        );
        RightPanelLayout.setVerticalGroup(
                RightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(RightPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(htmlScrollPane)
                                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(topPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(leftPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rightPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(topPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(leftPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(rightPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InputTextButtonActionPerformed(java.awt.event.ActionEvent evt) {

        // File loading
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File myFile = chooser.getSelectedFile();

        HTMLEditorKit kit = new HTMLEditorKit();
        htmlEditorPane.setEditorKit(kit);
        Document doc = kit.createDefaultDocument();

        htmlEditorPane.setDocument(doc);
        try {
            htmlEditorPane.setText(Jsoup.parse(myFile, "UTF-8", " ").html());
        } catch (IOException e) {
            e.printStackTrace();
        }

//        try {
//            // TODO: Replace with regular parsing, there is no apparent need for JSoup
//            Document doc = Jsoup.parse(myFile, "UTF-8", " ");
//
//            String documentText = parseDocument(doc.html());
//            TextPane.setText(documentText);
//            vocab = new Vocabulary(documentText);
//        } catch (IOException e) {
//            //JOptionPane.showMessageDialog(null, e);
//        }

    }

    private String parseDocument(String text) {
        String processedText = text;

        //Remove the <head> tag
        processedText = processedText.replaceAll("<head([\\s\\S]+?)</head>", "");
        //Remove the <title> tag
        processedText = processedText.replaceAll("<title([\\s\\S]+?)</title>", "");
        //Remove the <pre> tags
        processedText = processedText.replaceAll("<pre([\\s\\S]+?)</pre>", "");
        //Remove CSS style
        processedText = processedText.replaceAll("<style([\\s\\S]+?)</style>", "");
        //New line after each header
        processedText = processedText.replaceAll("<[/]h.>", "\n");
        //New line after each paragraph
        processedText = processedText.replaceAll("</p>", "\n");
        //Remove the rest of the html tags
        processedText = processedText.replaceAll("<[^>]*>", "");
        //Remove the &nbsp; characters
        processedText = processedText.replaceAll("&nbsp;", "");
        //Remove the &amp; characters
        processedText = processedText.replaceAll("&amp;", "");
        //Remove blank lines
        processedText = processedText.trim();

        return processedText;
    }

    public static void main(String args[]) throws IOException {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LiteratureAnalyticsUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LiteratureAnalyticsUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LiteratureAnalyticsUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LiteratureAnalyticsUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LiteratureAnalyticsUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton inputTextButton;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JPanel rightPanel;
    private javax.swing.JPanel topPanel;
    private javax.swing.JEditorPane htmlEditorPane;
    private javax.swing.JScrollPane htmlScrollPane;
    // End of variables declaration//GEN-END:variables
}
